apiVersion: apps/v1
kind: Deployment
metadata:
  name: swap-stat-api-deployment
  labels:
    app: swap-stat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swap-stat-api
  template:
    metadata:
      labels:
        app: swap-stat-api
    spec:
      containers:
        - name: swap-stat-api
          image: fountainchen/swap-stat-api:sha-a4c29bf
          ports:
            - containerPort: 8800
          env:
            - name: DS_URL
              value: "jdbc:postgresql://123.57.40.36:8432/starcoin?currentSchema=barnard"
            - name: DB_USER_NAME
              value: "starcoin"
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgresql-pw-starcoin
                  key: password
            - name: MAIN_DS_URL
              value: "jdbc:postgresql://123.57.40.36:8432/starcoin?currentSchema=main"